channels:
- conda-forge
dependencies:
- cereal
- cmake
- eigen
- freud
- fresnel
- gsd
- h5py
- ipywidgets
- jupyterlab
- ninja
- numpy>=2.0.0
- matplotlib
- mpi4py
- openmpi
- pillow
- pybind11
- python==3.12
- row
- signac
