ci:
  autoupdate_schedule: quarterly
  autofix_prs: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v5.0.0'
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: check-yaml
      - id: check-case-conflict
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        args:
          # Strip metadata but keep counts and outputs
          - --keep-count
          - --keep-output
          - --extra-keys
          - metadata.kernelspec cell.metadata.ExecuteTime
          - --drop-empty-cells
  - repo: https://github.com/bdice/nb-strip-paths
    rev: v0.1.0
    hooks:
      - id: nb-strip-paths
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff-format
        types_or: [ python, jupyter ]
      - id: ruff
        types_or: [ python, jupyter ]
